name: ci-dfa-api

on:
  pull_request:
    types: [opened, reopened, edited, synchronize]
    paths:
      - "src/**"
      - ".github/workflows/ci-dfa-api.yml"

env:
  IMAGE_NAME: dfa-api

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true

      - name: Build image
        working-directory: ./src
        run: tar -czh . | docker build --tag $IMAGE_NAME -
